### ISSUE TITLE
How to get 'score_mask'?

### ISSUE THREAD

**Issue by vintagew** [yuguangnudt/VEC_VAD#10]
When I run test.py: python test.py, I have a bug: File "test.py", line 411, in <module>
    cur_pixel_results = torch.load(os.path.join(results_dir, dataset_name, 'score_mask', '{}'.format(idx)))
  File "/home/**/.local/lib/python3.7/site-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'results/UCSDped2/score_mask/0' 

So, how I can get 'results/UCSDped2/score_mask/0 ? Looking forward to your reply.

**Comment by yuguangnudt** [comment]
> When I run test.py: python test.py, I have a bug: File "test.py", line 411, in
> cur_pixel_results = torch.load(os.path.join(results_dir, dataset_name, 'score_mask', '{}'.format(idx)))
> File "/home/**/.local/lib/python3.7/site-packages/torch/serialization.py", line 382, in load
> f = open(f, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'results/UCSDped2/score_mask/0'
> 
> So, how I can get 'results/UCSDped2/score_mask/0 ? Looking forward to your reply.

Please set 'scores_saved=False' (and 'test_foreground_saved=False', 'test_bbox_saved=False' if needed) in config.cfg to compute score mask first.

**Comment by vintagew** [comment]
Thanks for your reply. In config.cfg :
train_bbox_saved = False
train_foreground_saved = False
test_bbox_saved = False
test_foreground_saved = False
scores_saved = False

I followed the [README.md](https://github.com/yuguangnudt/VEC_VAD/blob/master/README.md) and the bug occurs after 'python test.py'. How to compute score mask first?

**Comment by vintagew** [comment]
Thanks for your reply. In config.cfg :
train_bbox_saved = False
train_foreground_saved = False
test_bbox_saved = False
test_foreground_saved = False
scores_saved = False

I followed the README.md and tested in UCSDped2 dataset. The bug occured after 'python test.py'. How to compute score mask first?

**Comment by yuguangnudt** [comment]
> Thanks for your reply. In config.cfg :
> train_bbox_saved = False
> train_foreground_saved = False
> test_bbox_saved = False
> test_foreground_saved = False
> scores_saved = False
> 
> I followed the README.md and tested in UCSDped2 dataset. The bug occured after 'python test.py'. How to compute score mask first?

Did you forget to set the dataset_name at line 2 in [shared_parameters]? First you should set 'dataset_name'  you want to test in [shared_parameters] in config.cfg, i.e. , dataset_name=UCSDped2 in your situation. Obviously, if you set 'scores_saved = False' the code should go to line 223 (if scores_saved is False:) to conduct anomaly detection (i.e. , score every frame to get score mask). But it seems you started evaluation (line 378) before anomaly detection.

**Comment by vintagew** [comment]
Inspired by your response, I found some problems with dataset path and file format. I have solved these problems. 
Now, I have a new question that needs your help when run 'python test.py'. The ground truths of all frames in a dataset all are 'False', so AUC cannot be calculated. Why I get all False labels of all frames? Could you give me some advices?
