### ISSUE TITLE
 saveSegNum

### ISSUE THREAD

**Issue by cuixianheng** [yuguangnudt/VEC_VAD#16]
Hi,

I am a question is in the config.cfg, the saveSegNum is  what means?

**Comment by yuguangnudt** [comment]
> 
> 
> Hi,
> 
> I am a question is in the config.cfg, the saveSegNum is what means?

saveSegNum is the length of each data segment when storing the foreground data of ShanghaiTech in segments. The reason for storing by segment is that ShanghaiTech is too large to load all of its foreground data into memory at once.
