### ISSUE TITLE
Unable to resolve requirements

### ISSUE THREAD

**Issue by OShapovalov** [yuguangnudt/VEC_VAD#2]
I am trying to reproduce your results, but can't reproduce your environment. Could you provide versions for mmdetection and mmcv? If you provide full conda env, it would be great.

**Comment by yuguangnudt** [comment]
> I am trying to reproduce your results, but can't reproduce your environment. Could you provide versions for mmdetection and mmcv? If you provide full conda env, it would be great.

Package                Version              
addict                 2.2.1          
albumentations         0.3.3          
certifi                2019.9.11      
chardet                3.0.4          
cycler                 0.10.0         
Cython                 0.29.13        
decorator              4.4.0          
h5py                   2.10.0         
idna                   2.8            
imagecorruptions       1.0.0          
imageio                2.6.1          
imgaug                 0.2.5          
joblib                 0.14.0         
Keras                  2.3.1          
Keras-Applications     1.0.8          
Keras-Preprocessing    1.1.0          
kiwisolver             1.1.0          
matplotlib             3.1.1          
_**mmcv                   0.2.14         
mmdet                  1.0rc0+b287273**_
networkx               2.3            
numpy                  1.17.2         
opencv-contrib-python  4.1.1.26       
opencv-python-headless 4.1.1.26       
Pillow                 6.2.0          
pip                    19.2.3         
pkg-resources          0.0.0          
pycocotools            2.0.0          
pyparsing              2.4.2          
pypng                  0.0.20         
python-dateutil        2.8.0          
PyWavelets             1.0.3          
PyYAML                 5.1.2          
raft                   1.4.1.3        
requests               2.22.0         
scikit-image           0.15.0         
scikit-learn           0.21.3         
scipy                  1.3.1          
setuptools             41.4.0         
Shapely                1.6.4.post2    
six                    1.12.0         
terminaltables         3.1.0          
torch                  1.1.0          
torchvision            0.3.0          
urllib3                1.25.6         
wheel                  0.33.6         

You can refer to the package list in my environment. Note that the version of mmdetection we were using at the time was [v1.0rc0](https://github.com/open-mmlab/mmdetection/tree/v1.0rc0), and its installation may be different from the latest. You can run the program strictly according to our version, or you can try the later versions of mmdetection and Pytorch. Good luck!
