### ISSUE TITLE
about the anomaly score and STCs

### ISSUE THREAD

**Issue by algorithmlixuan** [yuguangnudt/VEC_VAD#3]
> > hi, I have a question about your paper. A frame maybe have some STC, but the anomaly score in your method only one STC. When you judge whether an frame is an abnormal，are all STCs in this frame used?
> > I am very appreciate if you give me some advice
> 
> Of course all STCs are used. Due to the limitation of space in this paper, we only specify the calculation method of anomaly score of a STC instead of a whole frame. In the experiment, the largest STC anomaly score in a frame is used as the anomaly score for this frame. You can refer to lines 366-373 and 402-414 in test.py.

Hi, thanks for your inspiring work. I have a question:
why does one frame have some STCs? According to this figure in your paper, one STC should have multiple frames instead of multiple STCs per frame
And could you upload the supplementary material mentioned in your paper?
I am very appreciate if you give me some advice

![image](https://user-images.githubusercontent.com/30352320/96693146-73f14000-13b9-11eb-84c7-e2176d32ffa0.png)

_Originally posted by @algorithmlixuan in https://github.com/yuguangnudt/VEC_VAD/issues/1#issuecomment-713398277_

**Comment by yuguangnudt** [comment]
> > > hi, I have a question about your paper. A frame maybe have some STC, but the anomaly score in your method only one STC. When you judge whether an frame is an abnormal，are all STCs in this frame used?
> > > I am very appreciate if you give me some advice
> > 
> > 
> > Of course all STCs are used. Due to the limitation of space in this paper, we only specify the calculation method of anomaly score of a STC instead of a whole frame. In the experiment, the largest STC anomaly score in a frame is used as the anomaly score for this frame. You can refer to lines 366-373 and 402-414 in test.py.
> 
> Hi, thanks for your inspiring work. I have a question:
> why does one frame have some STCs? According to this figure in your paper, one STC should have multiple frames instead of multiple STCs per frame
> And could you upload the supplementary material mentioned in your paper?
> I am very appreciate if you give me some advice
> 
> ![image](https://user-images.githubusercontent.com/30352320/96693146-73f14000-13b9-11eb-84c7-e2176d32ffa0.png)
> 
> _Originally posted by @algorithmlixuan in [#1 (comment)](https://github.com/yuguangnudt/VEC_VAD/issues/1#issuecomment-713398277)_

Because a frame often contains multiple RoIs, and one RoI corresponds to one STC. For simplicity, we only show the construction of one STC in the figure.
Please find supplementary material at https://dl.acm.org/doi/10.1145/3394171.3413973 or https://www.researchgate.net/publication/344385397_mmfp0444_Supplementary_Materialpdf
