### ISSUE TITLE
where can I set different methods (VEC-A / VEC-AM) , like table1 

### ISSUE THREAD

**Issue by timchen91stu** [yuguangnudt/VEC_VAD#5]
Dear author, thanks for your perfect working. In your code, where can I set different methods (VEC-A / VEC-AM) , like table1 in the paper?  which parameters? or setting

**Comment by yuguangnudt** [comment]
> Dear author, thanks for your perfect working. In your code, where can I set different methods (VEC-A / VEC-AM) , like table1 in the paper? which parameters? or setting

The difference between VEC-AM and VEC-A is that VEC-AM uses IE type ensemble for both appearance and motion completion, while VEC-A uses IE type only for appearance completion. So please set context_of_num=0 in config.cfg for VEC-A (which means that it only complete 1 current optical flow patch), and set corresponding network structure to SelfCompleteNet4 (to complete 5 raw patch and 1 optical flow patch) in train.py (at line 306, 398) and test.py (at line 255, 272). Similarly, set context_frame_num=context_of_num=4 and SelfCompleteNetFull network for VEC-AM (to complete 5 raw patch and 5 optical flow patch).
