### ISSUE TITLE
train with new dataset

### ISSUE THREAD

**Issue by rrxi** [yuguangnudt/VEC_VAD#6]
Thanks for your great work.

How to train with other dataset, eg UCF_Crimes https://visionlab.uncc.edu/download/summary/60-data/477-ucf-anomaly-detection-dataset ?

**Comment by yuguangnudt** [comment]
> Thanks for your great work.
> 
> How to train with other dataset, eg UCF_Crimes https://visionlab.uncc.edu/download/summary/60-data/477-ucf-anomaly-detection-dataset ?

Sorry, we currently do not implement interfaces for other data sets. The core is to inherit the torch.utils.data.Dataset class in PyTorch and customize the reading and processing of related data sets. Once the Dataset is implemented, relevant datasets can be added to config.cfg for training and testing.
We have implemented avenue_dataset, ped_dataset, shanghaitech_dataset in vad_datasets.py. You can follow them to implement the reading and training of other data sets.
