### ISSUE TITLE
sence num in ShanghaiTech dataset

### ISSUE THREAD

**Issue by LiUzHiAn** [yuguangnudt/VEC_VAD#8]
Hi,

In your code [here](https://github.com/yuguangnudt/VEC_VAD/blob/master/vad_datasets.py#L691), it seems that you processed the whole ShanghaiTech dataset as a single scene but not a scene-by-scene fashion. Then you trained the model on the total ~30K frames, right?

**Comment by yuguangnudt** [comment]
> Hi,
> 
> In your code [here](https://github.com/yuguangnudt/VEC_VAD/blob/master/vad_datasets.py#L691), it seems that you processed the whole ShanghaiTech dataset as a single scene but not a scene-by-scene fashion. Then you trained the model on the total ~30K frames, right?

Yes. We followed the setting of most work to give a fair comparison of performance.

**Comment by LiUzHiAn** [comment]
Thanks for your quick reply. 

Another question I wanna ask is, during the optical flow extracting process, you resize the image to `(512, 384)` for ped2, Avenue, and ShanghaiTech dataset? I found FlowNet would cause some blur results for some images in this size.

**Comment by yuguangnudt** [comment]
> Thanks for your quick reply.
> 
> Another question I wanna ask is, during the optical flow extracting process, you resize the image to `(512, 384)` for ped2, Avenue, and ShanghaiTech dataset? I found FlowNet would cause some blur results for some images in this size.

Yeah, we used the pre-trained FlowNet2 model (https://github.com/vt-vl-lab/flownet2.pytorch) to estimate optical flow, which requires the input size of (512, 384). Of course there may be some blur results, especially when transfering the pre-trained model to other scenarios, but FlowNet2 has been able to estimate optical flow fairly well and help improve VAD.

**Comment by LiUzHiAn** [comment]
Ok, thank you. Have a nice day.
